### ISSUE TITLE
Automated Miner Recipe Critical To Output

### ISSUE THREAD

**Issue by vitharr137** [Zistack/Satisfactory-Optimizer#3]
Hello,

Love this tool, I have a customized set of recipe and supporting json files with minor tweaks to their groupings, but I've noticed that on the last two revisions of the tool, the recipe Automated Miner now must part of the chain to output a result and I'm not quite sure why. 

I have included the problem file for rocket fuel I'm working with that shows the strange need for it, and the supporting json files I've altered for reference if you're interested in taking a look

[rocketfuel.json](https://github.com/user-attachments/files/17317921/rocketfuel.json)
[recipes.json](https://github.com/user-attachments/files/17317922/recipes.json)
[machines.json](https://github.com/user-attachments/files/17317923/machines.json)
[node_types.json](https://github.com/user-attachments/files/17317924/node_types.json)
[well_types.json](https://github.com/user-attachments/files/17317925/well_types.json)
[items.json](https://github.com/user-attachments/files/17317926/items.json)

**Comment by Zistack** [comment]
Polymer resin is a byproduct of the production chain you're shooting for, but you don't allow the factory to produce it as a byproduct (Items are not allowed to be outputs unless you say so).  Adding anything that allows the polymer resin to be consumed (In your case, the polymer resin is being turned into plastic to make coated iron plates for portable miners) will make the problem feasible.  Adding unlimited polymer resin output makes the problem feasible without making it product extra stuff for no reason.

Here's a fixed version of your [rocketfuel.json](https://github.com/user-attachments/files/17334541/rocketfuel.json).
